//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOfConsignee
    {
        public long Id { get; set; }
        public long InvoiceId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string GSTIN { get; set; }
        public string State { get; set; }
        public Nullable<long> StateCode { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
