//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string State { get; set; }
        public Nullable<long> StateCode { get; set; }
        public string ReverseCharge { get; set; }
        public Nullable<long> TransportationModeId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> PaymentDetailId { get; set; }
        public Nullable<long> DetailOfConsigneeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DetailOfConsignee DetailOfConsignee { get; set; }
        public virtual Invoice Invoice1 { get; set; }
        public virtual Invoice Invoice2 { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
        public virtual TransportaionMode TransportaionMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
