//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportaionMode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportaionMode()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public long Id { get; set; }
        public string VechicleNo { get; set; }
        public Nullable<System.DateTime> DateOfSupply { get; set; }
        public string PlaceOfSupply { get; set; }
        public string Mode { get; set; }
        public Nullable<long> StateCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
